farao-community/farao-dependencies

pom.xml
=> Upgrade farao-parent version

pom.xml
=> Update version and add new dependency

pom.xml
=> Release1.1.0

pom.xml
Business version update. Farao-core goes from 3.6.0 to 3.7.0.
=> Upgrade farao-core to 3.7.0

pom.xml
=> Release1.2.1

pom.xml
- farao-core: 3.7.1 -> 3.9.1
- powsybl-core: 4.4.0 -> 4.8.0
- powsyble-rte-core: 3.4.0 -> 3.8.0
- powsybl-open-loadflow: 0.13.0 -> 0.20.0
- powsybl-balances-adjustement: 1.12.0
- powsybl-entsoe: 1.4.0
=> Versions upgrade

.github/workflow/release.yml
=> Add release workflow

pom.xml
Upgrade farao-core to version 3.9.2
=> Upgrade farao-core version to 3.9.2

pom.xml
=> Upgrade powsybl-entsoe to 1.4.1

pom.xml
Upgrade versions:
- farao-core: 3.9.4 -> 4.0.0
- powsybl-core: 4.8.0 -> 4.9.2
- powsybl-rte-core: 3.8.0 -> 3.9.0
- powsybl-entsoe: 1.4.1 -> 1.5.2
- powsybl-balances-adjustment: 1.12.0 -> 1.13.0
- powsybl-open-loadflow: 0.20.0 -> 0.22.0
=> Upgrade to last released versions

pom.xml
=> Upgrade farao-core to 4.0.1

pom.xml
=> Upgrade farao-core to 4.1.0

.github/workflows/release.yml
=> Delete both release and new release branches

pom.xml
=> Upgrade OLF to 0.22.1

pom.xml
=> Upgrade farao-core to 4.1.1

pom.xml
=> upgrade dependencies to latest release train

pom.xml
=> Adding farao voltage monitoring version and dependency

pom.xml
It adds the merging view dependency to the dependencies list
=> add merging view to dependencies

pom.xml
=> add angle monitoring

pom.xml
=> bump to farao-core 4.2.2

pom.xml
=> upgrade farao and open loadflow versions

pom.xml
=> Update versions of powsybl

pom.xml
=> Update versions of farao and OLF

pom.xml
=> upgrade farao core version to 4.2.6

pom.xml
=> Upgrade PowSyBl-entsoe to version 2.3.0

pom.xml
=> upgrade farao core version

pom.xml
=> upgrade farao-core and powsybl

pom.xml
=> revert upgrade of olf version 

pom.xml
=> upgrade powsybl entsoe version

pom.xml
=> migrate to java 17

pom.xml
=> upgrade dependencies linked to powsybl 6.0.1

pom.xml
=> upgrade farao 4.6.1 and add dependency for cgmes export

.github/workflows/release.yml
=> Adapt release workflow to enable releasing hotfixes

.github/workflows/release.yml
=> fix github checkout and jdk actions

pom.xml
=> Upgrade powsybl 6.0.2 and farao 4.6.2

pom.xml
=> Update depndencies linked to powsybl 6.1.1

pom.xml
=> add csa crac creator

pom.xml
=> Upgrade powsybl open rao

pom.xml
=> Upgrade to powsybl core 6.2.3

pom.xml
=> Upgrade powsybl, openrao and loadflow versions

pom.xml
=> upgrade to open load flow 1.8.1

pom.xml
=> upgrade to open load flow 1.8.2 on master

pom.xml
=> Change versions of powsybl open-rao, core, entsoe and open-loadflow

pom.xml
=> upgrade open rao version to 5.5.0 and powsybl core version to 6.3.1

pom.xml
=> Update powsybl open-rao 5.5.1

pom.xml
=> Upgrade openrao

pom.xml
=> Upgrade Open-loadflow version 1.11.1

pom.xml
Upgrade powsybl-core to  v6.4.0, powsybl-open-loadflow to v1.12.1, powsybl-open-rao to v6.0.0 and powsybl-entsoe to v2.10.0
=> upgrade powsybl versions

pom.xml
=> Upgrade OpenRao to version 6.0.2

pom.xml
=> Back to OLF 1.12.2

pom.xml
=> Upgrade Open LoadFlow version to 1.13.2 with memory fix

pom.xml
=> upgrade open rao version to v6.1.2 and core to v6.5.1

pom.xml
=> Upgrade OLF dependency to 1.14.0

pom.xml
=> Upgrade powsybl entsoe & core
